document.write('<!-- SEO Starts -->');
document.write('<title>PilcrowMicro | ' + page.title + '</title>');
document.write('<meta name="description" content="' + page.description + '">');
document.write('<!-- SEO End -->');
document.write('<!-- Favicons Start -->');
document.write('<link rel="apple-touch-icon" 		sizes="57x57" 		href="' + page.path + 'images/apple-icon-57x57.png">');
document.write('<link rel="apple-touch-icon" 		sizes="60x60" 		href="' + page.path + 'images/apple-icon-60x60.png">');
document.write('<link rel="apple-touch-icon" 		sizes="72x72" 		href="' + page.path + 'images/apple-icon-72x72.png">');
document.write('<link rel="apple-touch-icon" 		sizes="76x76" 		href="' + page.path + 'images/apple-icon-76x76.png">');
document.write('<link rel="apple-touch-icon" 		sizes="114x114" 	href="' + page.path + 'images/apple-icon-114x114.png">');
document.write('<link rel="apple-touch-icon" 		sizes="120x120" 	href="' + page.path + 'images/apple-icon-120x120.png">');
document.write('<link rel="apple-touch-icon" 		sizes="144x144" 	href="' + page.path + 'images/apple-icon-144x144.png">');
document.write('<link rel="apple-touch-icon" 		sizes="152x152" 	href="' + page.path + 'images/apple-icon-152x152.png">');
document.write('<link rel="apple-touch-icon" 		sizes="180x180" 	href="' + page.path + 'images/apple-icon-180x180.png">');
document.write('<link rel="icon" type="image/png" 	sizes="192x192"  	href="' + page.path + 'images/android-icon-192x192.png">');
document.write('<link rel="icon" type="image/png" 	sizes="32x32" 		href="' + page.path + 'images/favicon-32x32.png"	>');
document.write('<link rel="icon" type="image/png" 	sizes="96x96" 		href="' + page.path + 'images/favicon-96x96.png"	>');
document.write('<link rel="icon" type="image/png" 	sizes="16x16" 		href="' + page.path + 'images/favicon-16x16.png"	>');
document.write('<meta name="msapplication-TileImage" content="' + page.path + 'images/ms-icon-144x144.png">');
document.write('<!-- Favicons End -->');
document.write('<!-- API Includes -->');
document.write('<link href="https://fonts.googleapis.com/css2?family=Volkhov:wght@700&family=Montserrat:wght@400;700&family=Oxygen&display=swap" rel="stylesheet">');
document.write('<!-- CSS Includes -->');
document.write('<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">');
document.write('<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.0/animate.compat.min.css" crossorigin="anonymous">');
document.write('<link rel="stylesheet" href="' + page.path + 'styles/main.css">');
document.write('<!-- JS Includes -->');
document.write('<script src="' + page.path + 'js/functions.js"></script>');